### PR TITLE
Normalize slashes in filepath; explicit regex support

### LINKED ISSUE #17: filelist silently turns paths to regex and fails to download
Case in point: `csgo\resource\flash\sharedlib.swf`. I assume the `\r` gets compiled into `CR` and thus never finds the file to download.

### LINKED ISSUE #18: filelist does not normalize slashes
`csgo/resource/flash/sharedlib.swf` will not get downloaded as slashes are `\` in the manifest.

### LINKED ISSUE #30: Some specific file paths do not work
When working with a few games, I noticed that some paths seem to fail to be found. There doesn't seem to be any reason why these paths would fail, as you can use a more generic path or wildcard and the same, exact path you had originally specified is where it grabs the file from.

**Examples:**

DedicatedServer64\Sandbox.Game.dll **_does not work_**
DedicatedServer(.*)\Sandbox.Game.dll **_works_**
Sandbox.Game.dll **_works_**

The odd thing is that I can specify other files under that same DedicatedServer64 folder and they are found without issues. I suspect this may be related/the same as https://github.com/SteamRE/DepotDownloader/issues/17.

These are from the game server: https://steamdb.info/depot/367971/

### PR DESCRIPTION
**Pull request by xPaw**
Fixes #30
Fixes #18
Fixes #17

I opted for `regex:` prefix because otherwise all paths are converted to regex which is not great. This converts all `\` slashes into `/` both in the file list, and when matching (because manifests can contain that sometimes). Windows handles `/` just fine, there is no need to convert it back.

### CODE REVIEW

File: DepotDownloader/ContentDownloader.cs [hunk 1]
```diff
@@ -94,12 +94,13 @@ static bool TestIsFileIncluded( string filename )
             if ( !Config.UsingFileList )
                 return true;
 
-            foreach ( string fileListEntry in Config.FilesToDownload )
+            filename = filename.Replace( '\\', '/' );
+            
+            if ( Config.FilesToDownload.Contains( filename.ToLowerInvariant() ) )
```
Comment (yaakov-h) [inline DepotDownloader/ContentDownloader.cs:99]: I’d pass a StringComparer to the HashSet’s constructor instead.

Comment (xPaw) [reply DepotDownloader/ContentDownloader.cs:99]: I thought about it, doesn't that defeat the purpose of using a hashing set?

**Review by yaakov-h — APPROVED** [review]
